# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_base_version=26.3
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=0.3.0
maven_group=com.glisco
archives_base_name=interactic

# Dependencies
fabric_version=0.162.0+26.3

# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=21.0.0






